inherit_from:
  - .rubocop_airbnb.yml
  
  
Rails:
  Enabled: true
   
 # 文字数上限
LineLength:
  Max: 130
#ここにはrubocopで検証したくないファイルやフォルダを指定
AllCops:
  Exclude:
      - 'config.ru'
      - 'db/**/*'
      - 'bin/*'
      - 'config/**/*'
      - 'lib/**'
      - 'vendor/**/*'
      - 'path/ruby'
      - '.git/**/*'
      - '**/Gemfile'  
      - 'node_modules/**/*'
      - 'script/**/*'
      
# # 日本語でのコメントを許可
# AsciiComments:
#   Enabled: false

# # クラスのコメント必須を無視
# Documentation:
#   Enabled: false

# # モジュール名::クラス名の定義を許可
# ClassAndModuleChildren:
#   Enabled: false

# # 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
# Style/FrozenStringLiteralComment:
#   Enabled: false